### ISSUE TITLE
Missing ESC concepts

### ISSUE THREAD

**Issue by acka47** [hbz/vocabs-edu#23]
Starting to collect concepts missing in ESC classification.

**Comment by acka47** [comment]
For https://beta.oerworldmap.org/resource/urn:uuid:acd928d4-428f-11e5-8d09-54ee7558c81f these are: "Astronomy", "Biomedical Engineering"

**Comment by philboeselager** [comment]
@acka47 What's the status of this issue? Is it still valid?

**Comment by acka47** [comment]
Yes, we should leave it open if we thinka about extending esc at some point.

**Comment by karindr** [comment]
There are some more field missing:

- a lot of languages for "language acquisition" such as Latin and ancient Greek and many modern languages

- for "literature and linguistics" there are only English, Spanish and Portuguese

- "Technik" as it is taught at Schools

**Comment by acka47** [comment]
Won't fix. Closing.
