### ISSUE TITLE
Wrong prefLabel@de for Psychology in esc.ttl

### ISSUE THREAD

**Issue by schlawiner** [hbz/vocabs-edu#36]
In the esc.ttl vocabulary, the **"psychology"** concept (`:n0313`) has the wrong german prefLabel (**"Politikwissenschaft"**) - probably a copy/paste error from the concept directly above, which is the "political science" concept and has the same german label.

## concept above (correct german label):
```
n0312 a skos:Concept ;
    skos:broader :n031 ;
    skos:inScheme :scheme ;
    skos:notation "0312" ;
    skos:prefLabel "Politikwissenschaft"@de,
        "Political sciences and civics"@en .
```
## "psychology" concept with wrong german label (Politikwissenschaft)
```
:n0313 a skos:Concept ;
    skos:broader :n031 ;
    skos:inScheme :scheme ;
    skos:notation "0313" ;
    skos:prefLabel "Politikwissenschaft"@de,
        "Psychology"@en .

**Comment by acka47** [comment]
Thanks for the pointer, @schlawiner . I am curious: Are you using ESC in any application?

**Comment by schlawiner** [comment]
Thanks for the quick fix!
As for using the ESC in production - not yet, anyway :). I'm looking at a few different classification systems to use (and extend for psychology) for a person's fields of study in our upcoming Knowledge Graph. ESC is a promising candidate.
We (ZPID - Leibniz Institute for Psychology) are planning a semantic-web-based update of our [PSYNDEX database](https://psyndex.de) that integrates author profiles/authority files, including their qualifications and in which field of science these qualifications were obtained.
