### ISSUE TITLE
Claim and set up name space at w3id

### ISSUE THREAD

**Issue by acka47** [hbz/vocabs-edu#5]
See https://github.com/perma-id/w3id.org/blob/master/README.md for instructions.

Until now, I used `https://w3id.org/oer/isced-2013#` resp. `https://w3id.org/oer/isced-1997#` as name space. By now I tend to rather use `https://w3id.org/isced/2013/` resp. `https://w3id.org/isced/1997/`. This not only mean adjusting the name space but also using slash URIs instead of hash URIs. (Skosmos seems to play well with these.)

What do you think @literarymachine ?

**Comment by literarymachine** [comment]
> What do you think @literarymachine?

I don't have a good picture of how Skosmos works yet. But keep in mind that when using hash URIs, the Server never sees the fragment identifier; this means that w3id.org would only see https://w3id.org/oer/isced-1997 when using hash URIs and thus could not forward to a concept-specific Skosmos URI.

So: we might not even have a choice here. I'd go on and use slash URIs.

**Comment by acka47** [comment]
So, we will go on as suggested by me above, then. Wait for the pull request.

**Comment by acka47** [comment]
>  Wait for the pull request.

Merged it by myself...

**Comment by acka47** [comment]
For registering a w3id one basically has to write a `.htaccess` into a folder at https://github.com/perma-id/w3id.org. I don't know how to write this but will describe the behaviour I envision here. Hopefully, @dr0i will be able to help me with the .htaccess.

We have two vocabularies: ISCED-1997 and ISCED-2013. 

Their namespaces are: 
- `https://w3id.org/isced/1997/`
- `https://w3id.org/isced/2013/`

Thus, we will have to add the folder `isced` with a .htaccess pointing to Skosmos. 
- Skosmos should be running at https://skosmos.lobid.org/ (If it takes to long to get ssl running, we might start without it).
- `.htaccess` should be configured so that e.g.
  - https://w3id.org/isced/2013/n0111 is redirected (303) to https://skosmos.lobid.org/isced/2013/page/n0111
  - https://w3id.org/isced/1997/level0 is redirected (303) to https://skosmos.lobid.org/isced/1997/level0

**Comment by acka47** [comment]
> Skosmos should be running at https://skosmos.lobid.org/ 

We rather should use something generic. I suggest https://vocabs.lobid.org/. Relying on the different meaning of "vocabulary" in the RDF world vs. library community, we will also be able to also publish our RDF vocabs there alongside the SKOS cocnept schemes (which are also called "value vocabularies"). If there are no objections, I will apply for the SSL certificate for vocabs.lobid.org soon.

**Comment by acka47** [comment]
The SSL certificate for vocabs.lobid.org is already here. Will discuss with @dr0i setting up skosmos as needed.

**Comment by acka47** [comment]
As discussed with @literarymachine on chat I will set the redirect latest on Monday, for now pointing to the vocabs on GitHub.

**Comment by acka47** [comment]
By now, we decided to use the following namespace: `https://w3id.org/class/` for the educational classification as "class" both refers to "school class" and "_class_ification".

**Comment by acka47** [comment]
The redirect for ESC is up and running see https://w3id.org/class/esc/. But what about ISCED-1997. Until now, we use `https://w3id.org/isced/1997/` in the data. We will have to decide whether we want to move this also to the "class" namespace, e.g. `https://w3id.org/class/isced-1997/`. Then, we will have to set up the redirect.

**Comment by acka47** [comment]
Closing, as we have another solution for ISCED-1997 namespace in #13/#27.
